# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/tama-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter akari akari_kddi akatsuki akatsuki_kddi aurora aurora_kddi xz2c xz2c_kddi,$(TARGET_DEVICE)),)

endif
