# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/tama-common-kddi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter akari akari_kddi akatsuki akatsuki_kddi aurora xz2c,$(TARGET_DEVICE)),)

endif
