# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/tama/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter akari_kddi apollo_kddi akatsuki_kddi aurora_kddi,$(TARGET_DEVICE)),)

endif
