# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/tama/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter akari apollo akatsuki aurora,$(TARGET_DEVICE)),)

endif
